# Configuracion general
spring.application.name=demo-hexagon-architecture
server.port=8081

# Configuracion de H2 en memoria
spring.datasource.url=jdbc:h2:mem:demohexagon-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/consoleh2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

# Configuracion de loggin
logging.level.root=error
logging.level.com.example.hexagon.demo=error
logging.file.name=logs/demo-hexagon-architecture.log

# Configuracion para HealthCheck
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always