-- EMPLOYEES
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES (101, 'John', 'Doe', 'JDOE', '555-1234', CURRENT_DATE, 'AD_ASST', 3500, NULL, NULL, 10);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES (102, 'Maria', 'Lopez', 'MLOPEZ', '555-5678', CURRENT_DATE, 'SA_REP', 5000, 0.10, 101, 20);